apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: project-1
  source:
    path: 
    repoURL: https://github.com/emiakia/flask-argocd.git
    targetRevision: main
