apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
    imagePullSecrets:
    - name: ghcr-secret
      containers:
      - name: flask-app
        image: ghcr.io/emrankia/flask-app:v1
        ports:
        - containerPort: 5000
