apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: flask-app-project
  namespace: argocd
spec:
  description: Flask Application Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default  # or flask-app-project if you created a project
  source:
    repoURL: 'https://github.com/emiakia/flask-argocd.git'
    targetRevision: main
    path: '.'  # Path where your k8s manifests (deployment, service) are located
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
