apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default  # or flask-app-project if you created a project
  source:
    repoURL: 'https://github.com/yourusername/your-repo'
    targetRevision: HEAD
    path: '.'  # Path where your k8s manifests (deployment, service) are located
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
